config/routes.rb
Nihongo::Application.routes.draw do
  resources :decks do
    resources :cards do
      get "move_up"
      get "move_down"
    end
    
    get "reorder"
    get "shuffle"
    
    collection do
      get "test_flash"
    end
  end

  resources :users 
  resources :sessions 
  resources :registration do
    collection do
      get :confirmation
    end
  end
  
  match "logout" => "sessions#destroy", :via => :delete
  
  get "home/index"
  get "home/valid_user"
  
  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
  end
  
  def valid_user
    @user = User.find_by_email( params[:email] )
    respond_to do |format|
      format.js #valid_user.js.erb
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_login.html.erb
<p>
	<%= label_tag :password %>
	<%= password_field_tag :password %>
</p>
<p>
	<%= submit_tag 'Login', {id: 'action_button'} %>
</p>

app/views/home/_user_registration.html.erb
<p>
	<%= label_tag :password %>
	<%= password_field_tag :password %>
</p>
<p>
	<%= label_tag :password_confirmation %>
	<%= password_field_tag :password_confirmation %>
</p>
<p>
	<%= submit_tag 'Register', {id: 'action_button'} %>
</p>

app/views/home/index.html.erb
<header>
	<h1>Little White Cards</h1>
</header>

<%# TODO: Why didn't the page change when registered? %>

<div>
	<%= form_tag :users, id: 'home_form', remote: true do %>
		<div id="spinner">
			<div class="spinner">
			  <div class="bar1"></div>
			  <div class="bar2"></div>
				<div class="bar3"></div>
				<div class="bar4"></div>
				<div class="bar5"></div>
				<div class="bar6"></div>
				<div class="bar7"></div>
				<div class="bar8"></div>
				<div class="bar9"></div>
				<div class="bar10"></div>
				<div class="bar11"></div>
			  <div class="bar12"></div>
			</div>
		</div>
	
		<p>
			<%= label_tag :email %>
			<%= email_field_tag :email, '', placeholder: "Email", autocapitalize: "off" %>
		</p>
		
		<div id="additional_fields"></div>
	<% end %>
</div>

app/views/home/valid_user.js.erb
<% if @user %>

	// console.log( "user valid" );
	document.hide_spinner( );
	$("#additional_fields").html("<%= j( render( 'login' ) ) %>");
	$("#home_form").attr( "action", "<%= sessions_path %>" );
	
<% else %>

	// console.log( "user invalid" );
	document.hide_spinner( );
	<% @user = User.new %>
	$("#additional_fields").html("<%= j( render( 'user_registration' ) ) %>");
	$("#home_form").attr( "action", "<%= registration_index_path %>" );

<% end %>

document.show_additional_fields( );

$("#home_form").submit( function( ) {
	document.show_spinner( );
	return true;
});