config/routes.rb
Nihongo::Application.routes.draw do
  resources :decks do
    resources :cards do
      get "move_up"
      get "move_down"
    end
    
    get "reorder"
    get "shuffle"
    
    collection do
      get "test_flash"
    end
  end

  resources :users 
  resources :sessions 
  resources :registration do
    collection do
      get :confirmation
    end
  end
  
  match "logout" => "sessions#destroy", :via => :delete
  
  get "home/index"
  get "home/valid_user"
  
  root :to => 'home#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck

  attr_accessor :content
  
  acts_as_list :scope => :deck
  
  validates :content, presence: {message: "of a card cannot be blank"}
  validates :content, uniqueness: {scope: :deck_id, message: "for that card is already in this deck"}
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  before_filter :authenticate
  before_filter :load_deck
  before_filter :authorize
  
  def authorize
    unless current_user == @deck.user
      redirect_to root_url, alert: "You are not authorized to access that"
    end
  end
  
  def load_deck
    @deck = Deck.find( params[:deck_id] )
  end
  
  # GET /cards
  # GET /cards.json
  def index
    @cards = @deck.cards.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = @deck.cards.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
      format.js # show.js.erb
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = @deck.cards.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = @deck.cards.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = @deck.cards.build(params[:card])

    respond_to do |format|
      if @card.save
        # flash.now.notice = "\"#{@card.content}\" was added to the deck"
        format.html { redirect_to new_deck_card_url(@deck) }
        format.json { render json: @card, status: :created, location: @card }
        format.js
      else
        flash.now.alert = @card.errors.full_messages.join(', ')
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  
  def move_up
    @card = @deck.cards.find(params[:card_id])
    @card.move_higher
    
    respond_to do |format|
      format.html {redirect_to deck_reorder_url(@deck)}
      format.js
    end
  end
  
  def move_down
    @card = @deck.cards.find(params[:card_id])
    @card.move_lower
    
    respond_to do |format|
      format.html {redirect_to deck_reorder_url(@deck)}
      format.js
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = @deck.cards.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to [@deck,@card], notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = @deck.cards.find(params[:id])
    @card.destroy

    respond_to do |format|
      # flash.now.notice = "\"#{@card.content}\" was removed"
      format.html { redirect_to deck_cards_url(@deck) }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  
  def link_to_next text, current_card
    unless current_card.last?
      link_to( text, deck_card_path( current_card.deck, current_card.lower_item ), class: "next arrow_links", remote: true )
    else
      '<span class="arrow_links next"></span>'.html_safe
    end
  end
  
  def link_to_prev text, current_card
    unless current_card.first?
      link_to( text, deck_card_path( current_card.deck, current_card.higher_item ), class: "prev arrow_links", remote: true )
    else
      '<span class="arrow_links prev"></span>'.html_safe
    end
  end
  
end

app/views/cards/_big_card.html.erb
<%= link_to_prev '', @card %>

<div class="big_card">
	<div class="content"><%= @card.content %></div>
</div>

<%= link_to_next '', @card %>

app/views/cards/_card.html.erb
<li id="card_<%= card.id %>">
	<%= link_to '', deck_card_path(@deck, card), method: :delete, class: 'manage', remote: true, confirm: "Are you sure?  This cannot be undone." %>
	<div class="content">
		<span class="rest-in-place" data-url="<%= deck_card_path(@deck, card) %>" data-object="card" data-attribute="content">
			<%= card.content %>
		</span>
	</div>
</li>

app/views/cards/_form.html.erb
<%= form_for([@deck,@card], remote: true) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content, "Card Content" %><br />
    <%= f.text_field :content, placeholder: "New Card Content" %>
  </div>
  <div class="actions">
    <%= f.submit '+' %>
  </div>
<% end %>

app/views/cards/_show_card_header.html.erb
<%= @card.position %> / <%= @deck.cards.count %>
of deck "<%= @deck.name %>"

app/views/cards/create.js.erb
$("#flash_holder").html( "<%= j render( "shared/flash_messages" ) %>" );
$(".flash_msg").slideDown( "slow" )

<% unless @card.errors.size > 0 %>
	$("#card_content").val( "" );
	$("#new_cards").prepend( "<%= j render( @card ) %>" );
	$("#card_<%= @card.id %>").css( "display", "none" )
	$("#card_<%= @card.id %>").fadeIn( );
<% end %>


$("#card_<%= @card.id %> .rest-in-place").restInPlace( );
document.scale_card_content( );

app/views/cards/destroy.js.erb
$("#flash_holder").html( "<%= j render( "shared/flash_messages" ) %>" );
$(".flash_msg").slideDown( "slow" )
$("#card_<%= @card.id %>").fadeOut( "slow", function( ) {
	$("#card_<%= @card.id %>").remove( );
	$("#card_count").html( "<%= @deck.cards.count %>" );
});

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', [@deck,@card] %> |
<%= link_to 'Back', deck_cards_path(@deck) %>

app/views/cards/index.html.erb
<%# cards index %>

<%= content_for :page_header do %>
	<h1><span id="card_count"><%= @deck.cards.count %></span> Card Deck</h1>
	<%= link_to "Back to Decks", decks_path %>
<% end %>

<%= content_for :ribbon_links do %>
	<li>
		<h2>
			<span class="rest-in-place" data-url="<%= deck_path(@deck) %>" data-object="deck" data-attribute="name">
				<%= @deck.name %>
			</span>
		</h2>
	</li>
	<% if @deck.cards.count > 0 %>
		<li><%= link_to 'Play this Deck', deck_card_path(@deck, @deck.cards.first) %></li>
	<% end %>
	<li><%= link_to 'Add a New Card', new_deck_card_path(@deck) %></li>
	<li><%= link_to 'Reorder Deck', deck_reorder_path(@deck) %></li>
	<li class="destroy"><%= link_to 'Destroy this Deck', deck_path(@deck), method: :delete, confirm: "Are you sure? This cannot be undone." %></li>
<% end %>

<ol class="cards">
	<% @cards.each do |card| %>
		<%= render card %>
	<% end %>
</ol>

app/views/cards/move_down.js.erb
$("#cards_table").html( "<%= j render( 'decks/cards' ) %>" );

app/views/cards/move_up.js.erb
$("#cards_table").html( "<%= j render( 'decks/cards' ) %>" );

app/views/cards/new.html.erb
<%= content_for :page_header do %>
	<h1>New card for "<%= @deck.name %>"</h1>
<% end %>

<%= content_for :ribbon_links do %>
	<li><%= link_to 'Done', deck_cards_path(@deck) %></li>
<% end %>

<%= render 'form' %>

<ol id="new_cards" class="cards"></ol>

app/views/cards/show.html.erb
<%= content_for :page_header do %>
	<h1 id="card_header">
		<%= render 'show_card_header' %>
	</h1>
<% end %>

<%= content_for :ribbon_links do %>
	<li><%= link_to 'Done', decks_path %></li>
<% end %>

<div id="big_card">
	<%= render 'big_card' %>
</div>

app/views/cards/show.js.erb
$('#big_card').html( "<%= j render( 'big_card' ) %>" );
$('#card_header').html( "<%= j render( 'show_card_header' ) %>" );

document.scale_card_content( );