config/routes.rb
Nihongo::Application.routes.draw do
  resources :decks do
    resources :cards do
      get "move_up"
      get "move_down"
    end
    
    get "reorder"
    get "shuffle"
    
    collection do
      get "test_flash"
    end
  end

  resources :users 
  resources :sessions 
  resources :registration do
    collection do
      get :confirmation
    end
  end
  
  match "logout" => "sessions#destroy", :via => :delete
  
  get "home/index"
  get "home/valid_user"
  
  root :to => 'home#index'

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :cards, :order => :position, :dependent => :destroy
  
  attr_accessor :name
  
  validates :name, :presence => true
  
  def shuffle
    random_positions = (1..(self.cards.count)).to_a.shuffle
    self.cards.all.each_with_index do |card, index|
      card.position = random_positions[index]
      card.save
    end
  end
  
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  
  before_filter :authenticate
  before_filter :authorize, :only => [:reorder, :shuffle, :update, :destroy]
  
  def authorize
    @deck = Deck.find( params[:id] ) if params[:id]
    @deck = Deck.find( params[:deck_id] ) if params[:deck_id]
    
    unless current_user == @deck.user
      redirect_to root_url, alert: "You are not authorized to access that"
    end
  end
  
  # GET /decks
  # GET /decks.json
  def index
    if current_user
      @decks = current_user.decks.all
      
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @decks }
      end
    else
      respond_to do |format|
        format.html {redirect_to new_session_url, :notice => "You must login to access your decks"}
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def test_flash
    @decks = current_user.decks.all
    flash.now.alert = "This is a test alert thingy of the thing with a really long message thing that spans more than one line."
    render 'index'
  end
  
  def show
    @deck = Deck.find params[:id]
    respond_to do |format|
      format.json {render json: @deck}
    end
  end

  # GET /decks/new
  # GET /decks/new.json
  def new
    @deck = Deck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/1/edit
  def edit
    @deck = Deck.find(params[:id])
  end
  
  def reorder
    @deck = Deck.find( params[:deck_id] )
  end
  
  def shuffle
    @deck = Deck.find( params[:deck_id] )
    @deck.shuffle
    
    respond_to do |format|
      format.html {render 'reorder'}
      format.js #reorder.js.erb
    end
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(params[:deck])

    respond_to do |format|
      if @deck.save
        @deck.update_attribute( :user_id, current_user.id )
        format.html { redirect_to deck_cards_url(@deck), notice: 'Deck was successfully created.' }
        format.json { render json: @deck, status: :created, location: @deck }
      else
        format.html { render action: "new" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /decks/1
  # PUT /decks/1.json
  def update
    @deck = Deck.find(params[:id])

    respond_to do |format|
      if @deck.update_attributes(params[:deck])
        format.html { redirect_to deck_cards_url(@deck), notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_cards.html.erb
<table class="cards">
	<% @deck.cards.each do |card| %>
		<tr>
			<td><%= card.content %></td>
			<td>
				<% unless card.first? %>
					<%= link_to deck_card_move_up_path(@deck, card), :remote => true do %>
						<%= image_tag "up_arrow_32.png", alt: "up" %>
					<% end %>
				<% end %>
			</td>
			<td>
				<% unless card.last? %>
					<%= link_to deck_card_move_down_path(@deck,card), :remote => true do %>
						<%= image_tag "down_arrow_32.png", alt: "down" %>
					<% end %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>

app/views/decks/_deck.html.erb
<div class="content">
	<% if deck.cards.count > 0 %>
		<%= link_to deck.name, deck_card_path(deck, deck.cards.first) %>
	<% else %>
		<%= link_to deck.name, new_deck_card_path(deck) %>
		<%= link_to '(Add Cards)', new_deck_card_path(deck), class: 'sub' %>
	<% end %>
</div>

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'New Deck Name' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<%= link_to 'Show', deck_cards_path(@deck) %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<%# decks index %>

<%= content_for :page_header do %>
	<h1>Your Decks</h1>
<% end %>

<%= content_for :ribbon_links do %>
	<li><%= link_to 'New Deck', new_deck_path %></li>
<% end %>

<ol class="decks">
	<% @decks.each do |deck| %>
		<li>
			<%= link_to '', deck_cards_path(deck), class: "manage" %>
			<%= render deck %>
		</li>
	<% end %>
</ol>

app/views/decks/new.html.erb
<% content_for :page_header do %>
	<h1>New Deck</h1>
<% end %>

<% content_for :ribbon_links do %>
	<li><%= link_to 'Cancel', decks_path %></li>
<% end %>

<%= render 'form' %>

app/views/decks/reorder.html.erb
<%= content_for :page_header do %>
	<h1>Reorder</h1>
<% end %>

<%= content_for :ribbon_links do %>
	<li><%= link_to 'Shuffle', deck_shuffle_path(@deck), :remote => true %></li>
	<li><%= link_to "Done", deck_cards_path(@deck) %></li>
<% end %>


<div id="cards_table">
	<%= render 'cards' %>
</div>

app/views/decks/shuffle.js.erb
$("#cards_table").html( "<%= j render( 'cards' ) %>" );